[build]
  publish = "out"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18.19.0"

# Handle client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {Role = ["admin"]}

# Default redirect for SPA routing
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404
