import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navigation from "@/components/Navigation";
import Footer from "@/components/Footer";
import ClientBody from "./ClientBody";

const ivyModeBody = localFont({
  src: "./fonts/ivy-mode-body.ttf",
  variable: "--font-ivy-body",
  display: "swap",
});

const ivyPrestoHeadline = localFont({
  src: [
    {
      path: "./fonts/ivy-presto-headline.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/ivy-presto-headline-italic.otf",
      weight: "400",
      style: "italic",
    },
  ],
  variable: "--font-ivy-headline",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={`${ivyModeBody.variable} ${ivyPrestoHeadline.variable}`}
      data-element="document-root"
      data-name="Document Root"
    >
      <ClientBody>
        <header data-element="site-header" data-name="Site Header">
          <Navigation />
        </header>
        <main
          data-element="main-content"
          data-name="Main Content Area"
        >
          {children}
        </main>
        <Footer />
      </ClientBody>
    </html>
  );
}
